
# 🎯 Selecting and Indexing Data in Pandas

## 🎯 Learning Objectives

- Select rows and columns from a DataFrame.
- Understand label-based and position-based indexing.
- Use `loc[]` and `iloc[]` effectively.
- Apply Boolean Indexing.
- Set and reset indexes.

## 📖 Introduction

Selecting and indexing data is one of the most common tasks in Pandas. It allows you to retrieve specific rows, columns, or subsets of data efficiently for analysis, cleaning, and machine learning.

## 📌 Import Pandas

```python
import pandas as pd
```

In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [22, 25, 23, 24],
    "Marks": [85, 90, 78, 88],
    "City": ["Delhi", "Mumbai", "Pune", "Hyderabad"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Marks       City
0    Alice   22     85      Delhi
1      Bob   25     90     Mumbai
2  Charlie   23     78       Pune
3    David   24     88  Hyderabad

## 📌 Select a Single Column

Returns a Pandas Series.

```python
df["Name"]
```

In [2]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

## 📌 Select Multiple Columns

Returns a DataFrame.

```python
df[["Name", "Marks"]]
```

In [3]:
print(df[["Name", "Marks"]])

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     88

## 📌 `loc[]` (Label-Based Indexing)

Select rows and columns using index labels.

```python
df.loc[0]

df.loc[1:3]

df.loc[:, ["Name", "Marks"]]

df.loc[0:2, ["Name", "Age"]]
```

In [4]:
df.loc[0]

df.loc[1:3]

df.loc[:, ["Name", "Marks"]]

df.loc[0:2, ["Name", "Age"]]

      Name  Age
0    Alice   22
1      Bob   25
2  Charlie   23

## 📌 `iloc[]` (Position-Based Indexing)

Select rows and columns using integer positions.

```python
df.iloc[0]

df.iloc[0:3]

df.iloc[:, 1:3]

df.iloc[1:4, 0:2]
```

In [5]:
df.iloc[0]

Name     Alice
Age         22
Marks       85
City     Delhi
Name: 0, dtype: object

In [6]:
df.iloc[0:3]

      Name  Age  Marks    City
0    Alice   22     85   Delhi
1      Bob   25     90  Mumbai
2  Charlie   23     78    Pune

## 📌 Boolean Indexing

Filter data based on conditions.

```python
df[df["Marks"] > 85]

df[df["Age"] < 24]
```

In [7]:
df[df["Marks"] > 85]

    Name  Age  Marks       City
1    Bob   25     90     Mumbai
3  David   24     88  Hyderabad

## 📌 Multiple Conditions

Use `&` (AND) and `|` (OR).

```python
df[(df["Age"] > 22) & (df["Marks"] > 80)]

df[(df["City"] == "Pune") | (df["City"] == "Delhi")]
```

In [8]:
df[(df["Age"] > 22) & (df["Marks"] > 80)]

df[(df["City"] == "Pune") | (df["City"] == "Delhi")]

      Name  Age  Marks   City
0    Alice   22     85  Delhi
2  Charlie   23     78   Pune

## 📌 `set_index()`

Set a column as the DataFrame index.

```python
df.set_index("Name", inplace=True)

print(df)
```

## 📌 `reset_index()`

Restore the default integer index.

```python
df.reset_index(inplace=True)

print(df)
```

## 📌 Access Specific Values

```python
df.at[0, "Name"]

df.iat[0, 1]
```

| Method           | Purpose                                   |
| ---------------- | ----------------------------------------- |
| `df["Column"]`   | Select single column                      |
| `df[[...]]`      | Select multiple columns                   |
| `loc[]`          | Label-based indexing                      |
| `iloc[]`         | Position-based indexing                   |
| `at[]`           | Fast access to a single value by label    |
| `iat[]`          | Fast access to a single value by position |
| `set_index()`    | Set index                                 |
| `reset_index()`  | Reset index                               |
| Boolean Indexing | Filter rows                               |

## 📝 Summary

- Use `[]` to select columns.
- `loc[]` uses labels, while `iloc[]` uses integer positions.
- Boolean indexing filters data based on conditions.
- `set_index()` changes the index column.
- `reset_index()` restores the default index.
- `at[]` and `iat[]` provide fast access to individual values.