# ⚙️ Introduction to Feature Engineering

## 🎯 Learning Objectives

After completing this notebook, you will be able to:

- Understand what Feature Engineering is.
- Learn why Feature Engineering is important.
- Differentiate between features and variables.
- Understand the Feature Engineering pipeline.
- Learn different types of Feature Engineering techniques.
- Apply basic feature engineering using the Titanic dataset.

## 📖 Introduction

Feature Engineering is one of the most important steps in the Machine Learning pipeline.

A machine learning model learns patterns from the input features (columns). The better the quality of these features, the better the model's performance.

Feature Engineering is the process of creating, modifying, selecting, or transforming features to improve the accuracy and performance of machine learning models.

Many real-world machine learning projects spend more time on feature engineering than on model building.

## ❓ What is a Feature?

A Feature is an individual measurable property or characteristic used as input for a machine learning model.

Examples:

Age

Salary

Gender

Height

Weight

Marks

Experience

Each column in a dataset is usually considered a feature.

## 📚 Feature vs Target Variable

Feature (Independent Variable)

- Input provided to the model.
- Used to make predictions.

Examples:

Age

Fare

Pclass

Sex

---

Target Variable (Dependent Variable)

- Output the model predicts.

Example:

Titanic Dataset

Target Variable = Survived

## 💡 Why is Feature Engineering Important?

Good feature engineering can:

- Improve model accuracy.
- Reduce overfitting.
- Reduce training time.
- Improve model interpretability.
- Help algorithms learn patterns more effectively.

Bad features often lead to poor model performance, even if a powerful algorithm is used.

## 🔄 Machine Learning Pipeline

Raw Data

↓

Data Cleaning

↓

Feature Engineering

↓

Feature Selection

↓

Model Training

↓

Model Evaluation

↓

Prediction

## 📚 Types of Feature Engineering

Common Feature Engineering techniques include:

- Handling Missing Values
- Encoding Categorical Variables
- Feature Scaling
- Feature Transformation
- Feature Creation
- Feature Selection
- Handling Imbalanced Data
- Dimensionality Reduction

## 🌍 Real-World Example

Suppose we want to predict whether a customer will purchase a product.

Original Features:

- Age
- Salary
- City
- Gender

Engineered Features:

- Age Group
- Salary Category
- Years as Customer
- Total Purchases
- Average Purchase Value

These engineered features often improve the model's performance.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\Sanskruti\sanskruti document\Machine-Learning-From-Scratch\datasets\train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.shape

(891, 12)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## 📌 Identify Features and Target

In [6]:
X = df.drop("Survived", axis=1)

y = df["Survived"]

print("Features Shape:", X.shape)

print("Target Shape:", y.shape)

Features Shape: (891, 11)
Target Shape: (891,)

In [7]:
X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Observation:

All columns except Survived are features.

In [8]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

Observation:

The Survived column is the target variable.

In [9]:
df.select_dtypes(include=["int64","float64"]).columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [10]:
df.select_dtypes(include=["object"]).columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Observation:

Some features such as Age, Cabin, and Embarked contain missing values, which need to be handled before training a model.

## 📌 Feature Engineering in Titanic Dataset

| Original Feature | Possible Engineered Feature |
| ---------------- | --------------------------- |
| Age              | Age Group                   |
| Fare             | Fare Category               |
| Name             | Title (Mr, Mrs, Miss, etc.) |
| Cabin            | Deck                        |
| Ticket           | Ticket Prefix               |
| SibSp + Parch    | Family Size                 |

In [12]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

df[["SibSp", "Parch", "FamilySize"]].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

Explanation:

FamilySize represents the total number of family members traveling together, including the passenger.

In [13]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=["Child", "Teen", "Young Adult", "Adult", "Senior"]
)

df[["Age", "AgeGroup"]].head()

    Age     AgeGroup
0  22.0  Young Adult
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

Observation:

Continuous numerical data has been converted into meaningful categories.

## ✅ Benefits

- Improves prediction accuracy.
- Helps algorithms learn meaningful relationships.
- Reduces noise.
- Simplifies complex data.
- Improves model interpretability.

## 🔍 Observations

- Features are the inputs used by machine learning models.
- The target variable is the output to be predicted.
- Feature Engineering improves data quality before model training.
- Creating meaningful features often leads to better model performance.

## ✅ Best Practices

- Understand the dataset before creating new features.
- Avoid creating unnecessary features.
- Handle missing values before feature engineering.
- Document every engineered feature.
- Validate whether new features actually improve model performance.

## 🌍 Real-World Scenario

A bank wants to predict whether a customer will default on a loan.

Instead of using only the customer's monthly income, analysts create new features such as:

- Debt-to-Income Ratio
- Credit Utilization Percentage
- Average Monthly Spending
- Number of Late Payments

These engineered features provide more meaningful information and improve the model's ability to predict loan defaults.

## 📝 Summary

In this notebook, we introduced Feature Engineering, understood the difference between features and target variables, explored the machine learning pipeline, created new features using the Titanic dataset, and learned why feature engineering is one of the most important steps in building successful machine learning models.