# 🔤 Encoding Categorical Data

## 🎯 Learning Objectives

After completing this notebook, you will be able to:

- Understand categorical data.
- Learn why encoding is required.
- Differentiate between nominal and ordinal data.
- Apply Label Encoding.
- Apply One-Hot Encoding.
- Apply Ordinal Encoding.
- Understand Frequency Encoding.
- Get an introduction to Target Encoding and Binary Encoding.

## 📖 Introduction

Machine Learning algorithms work with numerical data, but real-world datasets often contain categorical features such as Gender, City, Education, or Country.

Encoding converts these categorical values into numerical values so that machine learning models can process them.

## ❓ What is Categorical Data?

Categorical data represents categories or labels instead of numerical values.

Examples:

- Male
- Female
- Red
- Blue
- Mumbai
- Pune

These values must be converted into numbers before training most machine learning models.

## 📚 Types of Categorical Data

### Nominal Data

No natural order exists.

Examples:

- Gender
- City
- Country
- Color

---

### Ordinal Data

Categories have a meaningful order.

Examples:

Education:

High School < Bachelor's < Master's < PhD

Customer Satisfaction:

Low < Medium < High

## 💡 Why Encoding?

Machine Learning algorithms perform mathematical operations.

Algorithms cannot directly understand text such as:

Male

Female

Mumbai

Delhi

Encoding converts these values into numbers while preserving useful information.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv(r"D:\Sanskruti\sanskruti document\Machine-Learning-From-Scratch\datasets\train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.select_dtypes(include="object").columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

## 📌 Label Encoding

Label Encoding assigns a unique integer to each category.

Example:

Male → 1

Female → 0

Best used for:

Binary categorical variables.

In [5]:
le = LabelEncoder()

df["Sex_Label"] = le.fit_transform(df["Sex"])

df[["Sex", "Sex_Label"]].head()

      Sex  Sex_Label
0    male          1
1  female          0
2  female          0
3  female          0
4    male          1

## 📌 One-Hot Encoding

One-Hot Encoding creates a new column for each category.

Example:

Embarked

C

Q

S

becomes

Embarked_C

Embarked_Q

Embarked_S

Best for Nominal Data.

In [6]:
embarked_encoded = pd.get_dummies(df["Embarked"], prefix="Embarked")

embarked_encoded.head()

   Embarked_C  Embarked_Q  Embarked_S
0       False       False        True
1        True       False       False
2       False       False        True
3       False       False        True
4       False       False        True

In [7]:
df = pd.concat([df, embarked_encoded], axis=1)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_Label,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,False,False,True

## 📌 Ordinal Encoding

Ordinal Encoding assigns numbers based on the natural order of categories.

Example:

Low → 0

Medium → 1

High → 2

Use only for Ordinal Data.

In [8]:
education = pd.DataFrame({
    "Education": [
        "High School",
        "Bachelor",
        "Master",
        "PhD",
        "Bachelor"
    ]
})

education

     Education
0  High School
1     Bachelor
2       Master
3          PhD
4     Bachelor

In [9]:
oe = OrdinalEncoder(
    categories=[[
        "High School",
        "Bachelor",
        "Master",
        "PhD"
    ]]
)

education["Education_Encoded"] = oe.fit_transform(
    education[["Education"]]
)

education

     Education  Education_Encoded
0  High School                0.0
1     Bachelor                1.0
2       Master                2.0
3          PhD                3.0
4     Bachelor                1.0

## 📌 Frequency Encoding

Frequency Encoding replaces each category with its frequency.

Example:

City

Mumbai → 250

Pune → 180

Delhi → 150

Useful when there are many categories.

In [10]:
frequency = df["Embarked"].value_counts()

frequency

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [11]:
df["Embarked_Frequency"] = df["Embarked"].map(frequency)

df[["Embarked","Embarked_Frequency"]].head()

  Embarked  Embarked_Frequency
0        S               644.0
1        C               168.0
2        S               644.0
3        S               644.0
4        S               644.0

## 📌 Target Encoding

Target Encoding replaces each category with the average value of the target variable.

Example:

Male

Average Survival = 0.18

Female

Average Survival = 0.74

Useful for high-cardinality categorical variables.

⚠️ Be careful to avoid data leakage.

In [12]:
target_encoding = df.groupby("Sex")["Survived"].mean()

target_encoding

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [13]:
df["Sex_Target"] = df["Sex"].map(target_encoding)

df[["Sex","Sex_Target"]].head()

      Sex  Sex_Target
0    male    0.188908
1  female    0.742038
2  female    0.742038
3  female    0.742038
4    male    0.188908

## 📌 Binary Encoding

Binary Encoding first assigns an integer to each category and then converts that integer into binary digits.

It is useful when a feature has many unique categories and One-Hot Encoding would create too many columns.

## 📌 Comparison of Encoding Techniques

| Encoding           | Best For              | Advantages                 | Disadvantages          |
| ------------------ | --------------------- | -------------------------- | ---------------------- |
| Label Encoding     | Binary categories     | Simple and fast            | May imply order        |
| One-Hot Encoding   | Nominal data          | No false ordering          | Creates many columns   |
| Ordinal Encoding   | Ordered categories    | Preserves order            | Only for ordinal data  |
| Frequency Encoding | High-cardinality data | Reduces dimensions         | Loses category meaning |
| Target Encoding    | High-cardinality data | Often improves performance | Risk of data leakage   |
| Binary Encoding    | Many categories       | Memory efficient           | Harder to interpret    |

## 🌍 Applications

Encoding is used in:

- Customer Churn Prediction
- House Price Prediction
- Fraud Detection
- Healthcare
- Recommendation Systems
- Credit Risk Analysis

## 🔍 Observations

- Machine learning algorithms require numerical input.
- Different encoding techniques are suitable for different types of categorical data.
- Choosing the right encoding method can improve model performance.

## ✅ Best Practices

- Use Label Encoding for binary variables.
- Use One-Hot Encoding for nominal categories.
- Use Ordinal Encoding only when categories have a natural order.
- Avoid high-dimensional One-Hot Encoding for features with many unique values.
- Be cautious of data leakage when using Target Encoding.

## 📝 Summary

In this notebook, we learned why categorical data must be encoded, explored Label Encoding, One-Hot Encoding, Ordinal Encoding, Frequency Encoding, and introduced Target Encoding and Binary Encoding using examples from the Titanic dataset.