# ⚖️ Feature Scaling and Encoding

## 🎯 Learning Objectives

After completing this notebook, you will be able to:

- Understand why categorical data must be encoded.
- Learn different encoding techniques.
- Understand why feature scaling is important.
- Apply StandardScaler, MinMaxScaler, and RobustScaler.
- Perform encoding and scaling on the Titanic dataset.

## 📖 Introduction

Machine learning models work with numerical data. Therefore, categorical features must be converted into numerical values through encoding. Additionally, numerical features often have different scales, which may negatively impact model performance.

Feature scaling standardizes numerical features, while encoding transforms categorical features into machine-readable formats.

## ❓ Why Encoding?

Machine learning algorithms cannot directly understand text values such as:

Male
Female

Cherbourg
Southampton

These values must be converted into numerical representations before model training.

## 📚 Common Encoding Techniques

- Label Encoding
- One-Hot Encoding
- Ordinal Encoding

In [1]:
import pandas as pd

from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    StandardScaler,
    MinMaxScaler,
    RobustScaler
)

In [2]:
df = pd.read_csv(r"D:\Sanskruti\sanskruti document\Machine-Learning-From-Scratch\datasets\train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Label Encoding

Label Encoding assigns a unique integer to each category.

Example

Male → 1

Female → 0

Best suited for binary or ordinal features.

In [3]:
le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])

df[["Sex"]].head()

   Sex
0    1
1    0
2    0
3    0
4    1

### One-Hot Encoding

Creates a separate column for each category.

Example

Embarked

S

C

Q

becomes

Embarked_C

Embarked_Q

Embarked_S

This avoids assigning numerical order where none exists.

In [4]:
encoded = pd.get_dummies(df["Embarked"], prefix="Embarked")

encoded.head()

   Embarked_C  Embarked_Q  Embarked_S
0       False       False        True
1        True       False       False
2       False       False        True
3       False       False        True
4       False       False        True

In [5]:
df = pd.concat([df, encoded], axis=1)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,False,False,True
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,False,False,True

## 📏 Why Feature Scaling?

Different features may have different ranges.

Example

Age → 5 to 80

Fare → 0 to 512

Large-scale features may dominate smaller ones during model training.

Scaling ensures all features contribute fairly.

### StandardScaler

Formula

z = (x − μ) / σ

Produces

Mean ≈ 0

Standard Deviation ≈ 1

Best used for algorithms such as Logistic Regression, SVM, and PCA.

In [6]:
scaler = StandardScaler()

df["Age_scaled"] = scaler.fit_transform(df[["Age"]].fillna(df["Age"].median()))

df[["Age","Age_scaled"]].head()

    Age  Age_scaled
0  22.0   -0.565736
1  38.0    0.663861
2  26.0   -0.258337
3  35.0    0.433312
4  35.0    0.433312

### MinMaxScaler

Transforms values between 0 and 1.

Useful for Neural Networks and KNN.

In [7]:
minmax = MinMaxScaler()

df["Fare_scaled"] = minmax.fit_transform(df[["Fare"]])

df[["Fare","Fare_scaled"]].head()

      Fare  Fare_scaled
0   7.2500     0.014151
1  71.2833     0.139136
2   7.9250     0.015469
3  53.1000     0.103644
4   8.0500     0.015713

### RobustScaler

Uses Median and IQR instead of Mean and Standard Deviation.

Best suited for datasets containing outliers.

In [8]:
robust = RobustScaler()

df["Fare_robust"] = robust.fit_transform(df[["Fare"]])

df[["Fare","Fare_robust"]].head()

      Fare  Fare_robust
0   7.2500    -0.312011
1  71.2833     2.461242
2   7.9250    -0.282777
3  53.1000     1.673732
4   8.0500    -0.277363

In [9]:
df[[
    "Age",
    "Age_scaled",
    "Fare",
    "Fare_scaled",
    "Fare_robust"
]].head()

    Age  Age_scaled     Fare  Fare_scaled  Fare_robust
0  22.0   -0.565736   7.2500     0.014151    -0.312011
1  38.0    0.663861  71.2833     0.139136     2.461242
2  26.0   -0.258337   7.9250     0.015469    -0.282777
3  35.0    0.433312  53.1000     0.103644     1.673732
4  35.0    0.433312   8.0500     0.015713    -0.277363

## 🔍 Observations

- Label Encoding converted the Sex column into numerical values.
- One-Hot Encoding created separate columns for each Embarked category.
- StandardScaler standardized the Age feature.
- MinMaxScaler transformed Fare into the range [0,1].
- RobustScaler handled the Fare feature while reducing the influence of outliers.

## 🌍 Real-World Scenario

A bank develops a loan approval model. Customer information includes categorical fields such as Gender and Marital Status, along with numerical features like Income and Loan Amount. Before training the model, categorical features are encoded and numerical features are scaled to improve model performance and ensure fair contribution from each feature.

## 📝 Summary

In this notebook, we learned how to convert categorical variables into numerical form using Label Encoding and One-Hot Encoding. We also explored StandardScaler, MinMaxScaler, and RobustScaler to normalize numerical features for machine learning models.